---
version: "3.8"
services:
  unifi-event-monitor:
    container_name: unifi-event-monitor
    image: interoperable/unifi-event-monitor:1.1.0
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./.apprise:/app/.apprise
      - ./blacklist.txt:/app/blacklist.txt
